name: Minify CSS

on:
  push:
    branches:
      - main  # 僅當 main 分支更新時觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install clean-css-cli -g

      - name: Minify CSS
        run: cleancss -o css/styles.min.css css/style.css

      - name: Commit and push minified CSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add css/styles.min.css
          git commit -m "Auto-minify CSS" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
