name: Minify CSS

on:
  push:
    branches:
      - main
    paths:
      - "css/style.css"  # ✅ 只監聽 style.css 的變更

permissions:
  contents: write  # 確保 GitHub Actions 有寫入權限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install clean-css-cli -g

      - name: Remove old minified CSS (確保 Git 偵測變更)
        run: rm -f css/style.min.css

      - name: Debug File Changes
        run: |
          echo "Before minification:"
          ls -l css/style.min.css || echo "style.min.css not found"
          echo "Running cleancss..."
          cleancss -o css/style.min.css css/style.css
          echo "After minification:"
          ls -l css/style.min.css

      - name: Check Git Changes
        run: |
          git add --force css/style.min.css
          git status  # ✅ 確認 Git 是否偵測變更
          git diff css/style.min.css || echo "No changes detected"

      - name: Commit and push minified CSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add css/style.min.css
          git status  # ✅ 再次確認 Git 變更
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit --allow-empty -m "Auto-minify CSS (forced update)"
            git pull --rebase origin main || true  # ✅ 避免衝突
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi
